# Generated by Django 2.1.4 on 2018-12-11 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='frequently',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='userdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=25, verbose_name='Names')),
                ('surname', models.CharField(max_length=25, verbose_name='Surname')),
                ('surname2', models.CharField(max_length=25, verbose_name='Surname')),
                ('Doc', models.CharField(max_length=15, verbose_name='Document')),
                ('birthday', models.DateTimeField(verbose_name='Birth Date')),
                ('pub_date', models.DateTimeField(verbose_name='Date published')),
            ],
        ),
        migrations.CreateModel(
            name='vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccinate', models.CharField(blank=True, max_length=50, null=True)),
                ('dose', models.CharField(choices=[('', ''), ('R', 'Recien Nacido'), ('U', 'Unica'), ('P', 'Primera'), ('S', 'Segunda'), ('T', 'Tercera'), ('A', 'Anual'), ('PR', 'Primer Refuerzo'), ('SR', 'Segundo Refuerzo')], default='', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esquema.userdate')),
            ],
        ),
    ]
